from UNKNOWN import PLAYER_WIDTH
import json, pygame
from Class.FUNC.RW_JSON import READ_WRITE


CONFIG_DIR = "C:\\Users\\leegu\\Desktop\\게임제작\\Config\\Main_Config.json"


class PLAYER:

    def PLAYER_INFO(CHAR_NAME, IMG_DIR):
        try:
            PLAYER_IMG = pygame.image.load(IMG_DIR)
            READ_CHARACTER_DATA = READ_WRITE.READ_JSON(CONFIG_DIR)["CHARACTER"]["PLAYER"][f"{CHAR_NAME}"]
            PLAYER_WIDTH = READ_CHARACTER_DATA["INFO"]["PLAYER_WIDTH"]
            PLAYER_HEIGHT = READ_CHARACTER_DATA["INFO"]["PLAYER_HEIGHT"]
            PLAYER_SPEED = READ_CHARACTER_DATA["INFO"]["PLAYER_SPEED"]
            
            return PLAYER_WIDTH, PLAYER_HEIGHT, PLAYER_IMG

        except:
            PLAYER_IMG = pygame.image.load(IMG_DIR)
            PLAYER_SIZE = PLAYER_IMG.get_rect().size
            PLAYER_SPEED = 15
            PLAYER_WIDTH = PLAYER_SIZE[0]
            PLAYER_HEIGHT = PLAYER_SIZE[1]
            READ_CONFIG_DATA = READ_WRITE.READ_JSON(CONFIG_DIR)
            with open(CONFIG_DIR, "w", encoding = "utf-8") as WRITE_CHARACTER_PROFILE:
                READ_CONFIG_DATA["CHARACTER"]["PLAYER"][f"{CHAR_NAME}"]["IMG_DIR"] = IMG_DIR
                READ_CONFIG_DATA["CHARACTER"]["PLAYER"][f"{CHAR_NAME}"]["INFO"]["PLAYER_WIDTH"] = PLAYER_WIDTH
                READ_CONFIG_DATA["CHARACTER"]["PLAYER"][f"{CHAR_NAME}"]["INFO"]["PLAYER_HEIGHT"] = PLAYER_HEIGHT
                READ_CONFIG_DATA["CHARACTER"]["PLAYER"][f"{CHAR_NAME}"]["INFO"]["PLAYER_SPEED"] = PLAYER_SPEED
                json.dump(READ_CONFIG_DATA, WRITE_CHARACTER_PROFILE, indent = 4)
            
            return PLAYER_WIDTH, PLAYER_HEIGHT, PLAYER_IMG

    def PLAYER_POS(CHAR_NAME):
        READ_CONFIG_DATA = READ_WRITE.READ_JSON(CONFIG_DIR)
        SCREEN_WIDTH = READ_CONFIG_DATA["DISPLAY"]["DISPLAY_1"]["DISPLAY_INFO"]["SCREEN_WIDTH"]
        SCREEN_HEIGHT = READ_CONFIG_DATA["DISPLAY"]["DISPLAY_1"]["DISPLAY_INFO"]["SCREEN_HEIGHT"]
        PLAYER_WIDTH = READ_CONFIG_DATA["CHARACTER"]["PLAYER"][f"{CHAR_NAME}"]["INFO"]["PLAYER_WIDTH"]
        PLAYER_HEIGHT = READ_CONFIG_DATA["CHARACTER"]["PLAYER"][f"{CHAR_NAME}"]["INFO"]["PLAYER_HEIGHT"]

        PLAYER_BASIC_X_POS = (SCREEN_WIDTH / 2) - (PLAYER_WIDTH / 2)
        PLAYER_BASIC_Y_POS = (SCREEN_HEIGHT / 2) - (PLAYER_HEIGHT / 2)

        return PLAYER_BASIC_X_POS, PLAYER_BASIC_Y_POS

    def PLAYER_MOVE(CHAR_NAME, NOW_EVENT, PLAYER_POS_LIST):
        """
        PLAYER_POS_LIST_TYPE = list
        PLAYER_POS_LIST[0] = PLAYER_X_POS
        PLAYER_POS_LIST[1] = PLAYER_Y_POS
        """
        READ_CONFIG_DATA = READ_WRITE.READ_JSON(CONFIG_DIR)
        PLAYER_SPEED = READ_CONFIG_DATA["CHARACTER"]["PLAYER"][f"{CHAR_NAME}"]["INFO"]["PLAYER_SPEED"]
        MOVE_X_POS = PLAYER_POS_LIST[0]
        MOVE_Y_POS = PLAYER_POS_LIST[1]

        EVENT_TYPE = NOW_EVENT.type

        if EVENT_TYPE == pygame.KEYDOWN:
            EVENT_KEY = NOW_EVENT.key
            if EVENT_KEY == pygame.K_UP:
                



